print('hello!')
print ('hi, i can code in python')
print ('hello!')
print ('here\'s a picture of a dog;')
print('o____')
print(' ||||')
print('my faworite animals are shhep')
print('o-###-')
print('  | |   #')
print('i love in glasgow')
print('  _|_ ')
print(' |   |' )
print(' |#  |____')
print(' |   |    |')
print(' |  #|  # |')
print('_|___|_#__|_')
print (' domek dla taty')
print('              _')
print('             | |/\ ')
print('             | /  \ ')
print('             |/    \ ')
print('             /      \ ')
print('            /   ___  \ ')
print('           /   |   |  \ ')
print('          /    |___|   \  ')
print('         /              \ ')
print('        /                \ ')
print('       /                  \ ')
print('      /                    \  ')
print('     /                      \ ')
print('    /|  _______             |\ ')
print('     | |   |   |            |')
print('     | |___|___|            |  ')
print('     | |   |   |            | ')
print('     | |___|___|  _________ |')
print('     |           |         ||')
print('     |           |         ||')
print('     |           | o-      ||')
print('     |           |         ||')
print('     |           |         ||')
print('     |           |         ||')
print(' ____|___________|_________||____')
print (' ')
print(' kwiatek  dla mamy')
print(' ')
print('       ______      ______   ')
print('      /      \___ /      \ ')
print('     |      _/   \_      | ')
print('     |     /        \    |  ')
print('     \     \  /\    /   / ')
print('      \    /  \/    \  /   ')
print('       \   \__/|\__ / /    ')
print('        \      |     /      ')
print('         \     |    /   ')
print('          \    |   /   ')
print('           \      /    ')
print('            \    /    ')
print('             \  /    ')
print('              \/     ')
